# Generated by Django 5.2.5 on 2025-08-13 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CorpsEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('char', 'Texte court'), ('text', 'Texte long'), ('decimal', 'Nombre décimal'), ('integer', 'Nombre entier'), ('select', 'Liste déroulante'), ('date', 'Date'), ('datetime', 'Date et heure'), ('boolean', 'Oui/Non'), ('file', 'Fichier'), ('photo', 'Photo')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteGenerale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('qualiticient', models.ManyToManyField(related_name='activites_generales_qualiticient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteSpecifique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('activite_generale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activitegenerale')),
            ],
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Detecter', 'Detecter'), ('En cours de traitement', 'En cours de traitement'), ('Résolu', 'Résolu')], default='Detecter', max_length=100)),
                ('delais', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='anomalies/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='anomalies/')),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('qualiticient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.controle')),
            ],
        ),
        migrations.CreateModel(
            name='AnomalieResolu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_anomalie_resolue1', models.ImageField(blank=True, null=True, upload_to='anomalies_resolues/')),
                ('photo_anomalie_resolue2', models.ImageField(blank=True, null=True, upload_to='anomalies_resolues/')),
                ('date_resolution', models.DateTimeField(auto_now_add=True)),
                ('anomalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='core.anomalie')),
            ],
        ),
        migrations.AddField(
            model_name='controle',
            name='corps_etat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corpsetat'),
        ),
        migrations.CreateModel(
            name='Entete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('activite_specifique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activitespecifique')),
            ],
        ),
        migrations.CreateModel(
            name='FicheControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('quantitemod', models.IntegerField(default=0, editable=False)),
                ('quantite_remplie', models.IntegerField(default=0)),
                ('etat_de_la_fiche', models.CharField(choices=[('Remplis', 'Remplis'), ('Validé', 'Validé')], default='Remplis', max_length=100)),
                ('signature_qualiticient', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_ingenieur_travaux', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('activite_generale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.activitegenerale')),
                ('activite_specifique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activitespecifique')),
                ('controle', models.ManyToManyField(to='core.controle')),
                ('ingenieur_travaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_ingenieur', to=settings.AUTH_USER_MODEL)),
                ('qualiticient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_qualiticient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnteteValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(blank=True, max_length=100, null=True)),
                ('entete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entete')),
                ('fiche_controle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entete_values', to='core.fichecontrole')),
            ],
        ),
        migrations.CreateModel(
            name='FicheRempli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_de_la_fiche', models.CharField(choices=[('En cours', 'En cours'), ('Remplis', 'Remplis'), ('Validé', 'Validé')], default='En cours', max_length=100)),
                ('signature_qualiticient', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_ingenieur_travaux', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='controle-qualité')),
                ('entetes_values', models.JSONField(default=list)),
                ('controles_values', models.JSONField(default=list)),
                ('tableaux_values', models.JSONField(blank=True, default=list, help_text='Stocke les tableaux dynamiques de la fiche si besoin.', null=True)),
                ('date_remplissage', models.DateTimeField(blank=True, null=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_remplies', to='core.fichecontrole')),
                ('ingenieur_travaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_remplies_ingenieur', to=settings.AUTH_USER_MODEL)),
                ('qualiticient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_remplies_qualiticient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anomalie',
            name='fiche_rempli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.ficherempli'),
        ),
        migrations.CreateModel(
            name='PlanReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('plan', models.FileField(upload_to='plans/')),
                ('activite_specifique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activitespecifique')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('Emplacement', models.CharField(max_length=100)),
                ('Reference_affaire', models.CharField(max_length=100)),
                ('coordonnateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_coordonnes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('activite_generale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activitegenerale')),
            ],
        ),
        migrations.CreateModel(
            name='SousProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_projets_chef_projet', to=settings.AUTH_USER_MODEL)),
                ('ingenieur_travaux', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_projets_ingenieur_travaux', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projet')),
            ],
        ),
        migrations.AddField(
            model_name='activitegenerale',
            name='sous_projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sousprojet'),
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=100)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
            ],
        ),
        migrations.AddField(
            model_name='anomalie',
            name='technicien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technicien'),
        ),
        migrations.CreateModel(
            name='ChampControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_champ', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('obligatoire', models.BooleanField(default=True)),
                ('options', models.TextField(blank=True, help_text='Options séparées par virgules pour select', null=True)),
                ('valeur_defaut', models.CharField(blank=True, max_length=200, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='core.controle')),
                ('type_champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typechamp')),
            ],
            options={
                'ordering': ['ordre', 'nom_champ'],
                'unique_together': {('controle', 'nom_champ')},
            },
        ),
    ]
