# Generated by Django 5.2.5 on 2025-08-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicien',
            name='role',
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='technicien',
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='status',
            field=models.CharField(choices=[('Detecter', 'Detecter'), ('Résolu', 'Résolu')], default='Detecter', max_length=100),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Technicien',
        ),
    ]
