# Generated by Django 5.2.5 on 2025-08-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_technicien_role_remove_anomalie_technicien_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entete',
            name='activite_specifique',
        ),
        migrations.RemoveField(
            model_name='entetevalue',
            name='fiche_controle',
        ),
        migrations.AddField(
            model_name='entete',
            name='fiche_controle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entetes', to='core.fichecontrole'),
        ),
        migrations.AddField(
            model_name='entetevalue',
            name='fiche_rempli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entete_values', to='core.ficherempli'),
        ),
        migrations.AddField(
            model_name='fichecontrole',
            name='titre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entetevalue',
            name='entete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.entete'),
        ),
    ]
